"""add external Camden parking bays

Revision ID: 1383148ede99
Revises: c8a21d45e901
Create Date: 2026-09-04 12:42:27.882972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1383148ede99'
down_revision: Union[str, Sequence[str], None] = 'c8a21d45e901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_parking_bays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_identifier', sa.String(length=100), nullable=False),
    sa.Column('restriction_type', sa.String(length=150), nullable=False),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('times_of_operation', sa.String(length=255), nullable=True),
    sa.Column('maximum_stay', sa.String(length=100), nullable=True),
    sa.Column('tariff', sa.Text(), nullable=True),
    sa.Column('cashless_identifier', sa.String(length=100), nullable=True),
    sa.Column('road_name', sa.String(length=150), nullable=False),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('controlled_parking_zone', sa.String(length=50), nullable=True),
    sa.Column('valid_parking_permits', sa.Text(), nullable=True),
    sa.Column('parking_bay_length_metres', sa.Float(), nullable=True),
    sa.Column('easting', sa.Float(), nullable=True),
    sa.Column('northing', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('spatial_accuracy', sa.String(length=100), nullable=True),
    sa.Column('source_last_uploaded', sa.DateTime(), nullable=True),
    sa.Column('organisation_uri', sa.Text(), nullable=True),
    sa.Column('source_dataset', sa.String(length=150), nullable=False),
    sa.Column('source_organisation', sa.String(length=150), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_parking_bays_controlled_parking_zone'), 'external_parking_bays', ['controlled_parking_zone'], unique=False)
    op.create_index(op.f('ix_external_parking_bays_latitude'), 'external_parking_bays', ['latitude'], unique=False)
    op.create_index(op.f('ix_external_parking_bays_longitude'), 'external_parking_bays', ['longitude'], unique=False)
    op.create_index(op.f('ix_external_parking_bays_postcode'), 'external_parking_bays', ['postcode'], unique=False)
    op.create_index(op.f('ix_external_parking_bays_road_name'), 'external_parking_bays', ['road_name'], unique=False)
    op.create_index(op.f('ix_external_parking_bays_source_identifier'), 'external_parking_bays', ['source_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_parking_bays_source_identifier'), table_name='external_parking_bays')
    op.drop_index(op.f('ix_external_parking_bays_road_name'), table_name='external_parking_bays')
    op.drop_index(op.f('ix_external_parking_bays_postcode'), table_name='external_parking_bays')
    op.drop_index(op.f('ix_external_parking_bays_longitude'), table_name='external_parking_bays')
    op.drop_index(op.f('ix_external_parking_bays_latitude'), table_name='external_parking_bays')
    op.drop_index(op.f('ix_external_parking_bays_controlled_parking_zone'), table_name='external_parking_bays')
    op.drop_table('external_parking_bays')
    # ### end Alembic commands ###
